### ISSUE TITLE
List of cards

### ISSUE THREAD

**Issue by agonkarimani** [agonkarimani/capstone-project#1]
### **Value statement - a requirement, not a solution**

As a user 
I want to see a list of places with basic informations about each place

### **Description**
<img width="373" alt="Bildschirmfoto 2021-06-04 um 16 54 38" src="https://user-images.githubusercontent.com/77042782/120821481-c866bb80-c555-11eb-9347-89a564ec0b0c.png">

### **Acceptance criteria**

- [ ] Card should consist of title, paragraph, tags and a hide & show button
- [ ] Click on button hides all information (title never hidden)
- [ ] List should be scrollable
- [ ] Card should contain information about place

### **Tasks**

- [ ] Feature branch
- [ ] Button component w/ storybook and tests
- [ ] Form component w/ storybook and test
- [ ] Update App with components and logic
- [ ] Add localStorage

**Comment by agonkarimani** [comment]
### **Value statement - a requirement, not a solution**

As a user
I want to see a card showing pictures and information about the place

### **Description**
<img width="280" alt="Bildschirmfoto 2021-06-03 um 10 10 35" src="https://user-images.githubusercontent.com/77042782/120661571-b1a66300-c488-11eb-9353-a1a9bc14385c.png">

### **Acceptance criteria**

- [ ] Card should consist of title, paragraph, tags and images
- [ ] Card should have a go back button
- [ ] Information and images 
- [ ] should be scrollable

### **Tasks**

- [ ] Feature branch
- [ ] Button component w/ storybook and tests
- [ ] Form component w/ storybook and test
- [ ] Update App with components and logic
- [ ] Add localStorage

**Comment by badabam** [comment]
"On click open card for more details" das steht oben in deinem Value statement. Das passt nicht, da du das hier nicht baust. Bitte schau dir die UserStories der anderen genau an.
