### ISSUE TITLE
Open card

### ISSUE THREAD

**Issue by agonkarimani** [agonkarimani/capstone-project#2]
As a user
I want to see a card showing pictures and detail information about the place on click

### **Description**
<img width="361" alt="Bildschirmfoto 2021-06-04 um 00 16 11" src="https://user-images.githubusercontent.com/77042782/120719356-6b71f380-c4ca-11eb-9e83-8023c1370eaa.png">

### **Acceptance criteria**

- [ ] Open card on click
- [ ] Card should consist of title, paragraph, tags and images
- [ ] Card should have a go back button
- [ ] Information and images 
- [ ] should be scrollable

### **Tasks**

- [ ] Feature branch
- [ ] Button component w/ storybook and tests
- [ ] Form component w/ storybook and test
- [ ] Update App with components and logic
- [ ] Add localStorage
