### ISSUE TITLE
Bookmark and navbar

### ISSUE THREAD

**Issue by agonkarimani** [agonkarimani/capstone-project#3]
### **Value statement - a requirement, not a solution**

As a user
I want to see bookmarked cards seprate to save them
I also need a small navbar to switch between bookmarked cards and not bookmarked cards

### **Description**
<img width="372" alt="Bildschirmfoto 2021-06-04 um 17 02 33" src="https://user-images.githubusercontent.com/77042782/120822553-cfda9480-c556-11eb-8506-25b538f3cd86.png">

### **Acceptance criteria**

- [ ] List of bookmarked cards
- [ ] bookmark creation 
- [ ] small navbar for switching

### **Tasks**

- [ ] Create feature branch
- [ ] Create component
- [ ] Add logic
- [ ] Add basic styling
- [ ] Create test
