### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by agonkarimani** [agonkarimani/capstone-project#4]
### **Value statement - a requirement, not a solution**

As a user
I want to see map of the Balkans with the places

### **Discription** 

<img width="386" alt="Bildschirmfoto 2021-06-04 um 17 07 49" src="https://user-images.githubusercontent.com/77042782/120823284-93f3ff00-c557-11eb-86ff-1986c61fc738.png">

### **Acceptance criteria**

- [ ] Fetch map of the region 
- [ ] show map 

### **Tasks**

- [ ] Create feature branch
- [ ] Create component
- [ ] Add logic
- [ ] Add basic styling
- [ ] Create test
