### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by agonkarimani** [agonkarimani/capstone-project#5]
### **Value statement - a requirement, not a solution**

As a user
I want switch with the navbar

### **Discription**

<img width="396" alt="Bildschirmfoto 2021-06-04 um 00 16 49" src="https://user-images.githubusercontent.com/77042782/120720845-14215280-c4cd-11eb-92a2-534f76c6cb7b.png">

### **Acceptance criteria**

- [ ] Add Navbar with all points 
- [ ] show current page

### **Tasks**

- [ ] Create feature branch
- [ ] Create component
- [ ] Add logic
- [ ] Add basic styling
- [ ] Create test
